# Generated by Django 5.0.1 on 2024-02-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
